### PR TITLE
Updates for PureScript 0.14

### PR DESCRIPTION
**Pull request by nsaunders**

### CODE REVIEW

**Comment by roryc89** [comment]
The new version of `sepByEnd` and `sepByEnd1` cause `listish` to fail when there is white space after the last element in a list.

**Comment by nsaunders** [comment]
> The new version of `sepByEnd` and `sepByEnd1` cause `listish` to fail when there is white space after the last element in a list.

Hi @roryc89, thanks for reviewing... I’m not entirely sure when I’ll have a chance to evaluate/fix that, but, if you want, you can feel free to open a PR targeting my ps-0.14 branch or open a new PR here and I’ll close this one. Otherwise, I’ll take a look as soon as I can!

**Comment by roryc89** [comment]
Hi @nsaunders no problem :) I've already made of copy of this project and updated it to purs 0.14 as my project has it a dependency. So I've made a PR targeting your PR.

**Comment by mikesol** [comment]
Hi, apologies for the delay, merged :rocket:

**Pull request merged**
